CREATE TABLE `rex_file_category` ( `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY, `name` VARCHAR(255) NOT NULL );
ALTER TABLE `rex_article` ADD `linkname` VARCHAR(255) NOT NULL AFTER `name`;
ALTER TABLE `rex_file` ADD `re_file_id` INT DEFAULT '0' NOT NULL AFTER `file_id`;
ALTER TABLE `rex_file` ADD `category_id` INT NOT NULL AFTER `re_file_id`;
ALTER TABLE `rex__board` ADD `anonymous_user` VARCHAR(50) NOT NULL AFTER `status`;
CREATE TABLE `rex_action` ( `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY, `name` VARCHAR(255) NOT NULL, `action` TEXT NOT NULL, `prepost` TINYINT NOT NULL, `status` TINYINT NOT NULL );
CREATE TABLE `rex_module_action` ( `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY, `module_id` INT NOT NULL, `action_id` INT NOT NULL );
CREATE TABLE rex__session ( session varchar(50) NOT NULL default '', user_id int(11) NOT NULL default '0', name varchar(50) NOT NULL default '', stamp int(11) NOT NULL default '0', PRIMARY KEY  (session));
ALTER TABLE `rex_file_category` ADD `re_id` INT NOT NULL, ADD `path` VARCHAR(255) NOT NULL;
ALTER TABLE `rex_file` ADD `user_login` VARCHAR(255) NOT NULL;
ALTER TABLE `rex_file` ADD `width` INT NOT NULL, ADD `height` INT NOT NULL, ADD `title` VARCHAR(255) NOT NULL, ADD `description` TEXT NOT NULL, ADD `copyright` VARCHAR(255) NOT NULL, ADD `stamp` INT NOT NULL;
ALTER TABLE `rex_article` ADD `user_login` VARCHAR(255) NOT NULL;
ALTER TABLE `rex_category` ADD `description` TEXT NOT NULL, ADD `func` TEXT NOT NULL;